# Generated by Django 5.1.6 on 2025-04-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_album_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='link',
            field=models.TextField(blank=True, default='#'),
        ),
    ]
