# Generated by Django 5.1.6 on 2025-04-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_band_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='link',
            field=models.URLField(blank=True, default='#'),
        ),
        migrations.AlterField(
            model_name='band',
            name='link',
            field=models.URLField(blank=True, default='#'),
        ),
    ]
